version: '3.8'

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0:11434
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/tags"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    networks:
      - app-network

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: fastapi_generator
    ports:
      - "8080:8080"
    environment:
      - OLLAMA_HOST=http://ollama:11434
      - CODE_MODEL=qwen2.5-coder:7b
      - VISION_MODEL=llama3.2-vision
      - MAX_PAGES=5
      - MAX_DESCRIPTION_LENGTH=2000
      - MAX_IMAGES=3
      - MAX_IMAGE_SIZE_MB=5
      - REQUEST_TIMEOUT=300
      - RATE_LIMIT_PER_MINUTE=10
    depends_on:
      ollama:
        condition: service_started
    restart: unless-stopped
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

volumes:
  ollama_data:
    driver: local

networks:
  app-network:
    driver: bridge
